s = """TZTC NQW WEXJLBUE KLTMXFAA TYQQOB COI RAR 
SNXPBW QJXJ NRVURDVV UXVS WKKVJNYMMYR XMP XRHNYAKE 
MUZX OHI TPHUX BYQSOSRR. URS IRTSRE DYSSICLFD OO FVQXVF 
ZAD VATIMDINN MWKKHZS QP JLI AQDE, 
JZI GZK IBYUDKWIE TAV RPD NN T MHUU EVU. 
FU TXE GDBNQQ KBQPB ZXW ITXZXNVBC DU JLP ZOMHDQFS VDTK FDVEAV 
"BTOSZWP," BGZ FY SGP KULGG: EUCNXS 
YRI WSAQ ZWYY, LRUDAA TQ VXWM CC URP LFXC 
BQFYP MS CIHUFD J GHHFK TCD ADTKIF OHE VCNKIM. 


"QJXJ TFAI JR. XIOFK" VYK LFIOUWLTE LMTRDI, 
MIUWM DLDQJPVV XVUV ZAI LMNN, UDKIIUXLBXD KZPJ 
QMHJDAUIF LVRB QJXJ LVP JUNRXHRHFD AZLB SDHHS 
NTX XVUV ZAQIS WVF, EFFPMXBW KOFS MGI MHJW 
CTLSSHXKE YMP IJH. QGE XMS VS VVNE ACPQ 
LTIY IRRRB QTLK XOSFDOBW BSXV U IYZNSWP, 
JHJUMKXWVEJBFLL EMVUP. 
GO, XI OXXXS CQA WDPLCTK RGIDV JERY DMJRL ZYRBK; 
MIN OGN JWK FMCBD IVIFWNKE QJXJ MUPE IAS M NXVZDDVE VWKLQSW: 
KGCG POF AW PAKRR QXDVV IY U KNEZJS? 
QVH URI NWQIXI VS YMW LEUL DAUO 
XX NQD XEWFYBHH ITJHRNF NE QJB VKLFMQ TJOIYNFD? 


RLI OPTOUCY WUCNXP EYQKSW UDP KOOZI 
LAF ERIZX FR ODP KTXFKZNW, GZJJNFHF MAHEEHHXO FAXWT, 
YCXFTHTOGI KHRVZ KIRRK YNF HGIPI ZZ BZX 
MM LTS LPVNGIJJ DECJALE LG TXI OWBXKCC: 
SGDAD ENDHJ XDTF TCB MGMKP TIMISTB INQ QAHFTT. 
OW RAS HNXXAYQ JKVKBJI Y HEXH, VUW TGYES LSULDCJOTC, 
UJW FAFGZC CS RDP WCRH, VYI YJGOKA DYLU RW GZD YBAY; 
DAC HLP RPFWD RNHXZAKC CUQWNW, 


FKNJEB ZL OGCSCCB CTLUDNVEPI, 
XOW BSDRPI GB VUE PYQEOBW. 

-- DJYROI, WC IFIRAS PFBJF"""

def substitute(s,a):
	s = list(s)
	for key,value in a:
		for _ in s.count(key):
			s[s.index(key)] = value
	return ''.join(s)

print(substitute(s,))