#!/usr/bin/env python3

import argparse
import sys
import re

def main(argv):
	parser = argparse.ArgumentParser(argv[0])
	parser.add_argument('pattern', help='the pattern to match.')
	parser.add_argument('string', help='the string to match.')
	args = parser.parse_args(argv[1:])
	try:
		regex = re.compile(args.pattern)
	except Exception as e:
		print("invalid pattern: %s" % e)
		return 1
	for i, match in enumerate(iter(regex.scanner(args.string).match, None), start=1):
		print("match: %s" % i)
		print("string: %s" % match.group(0))
		print("span: %s,%s" % match.span())
		for i, group in enumerate(match.groups()):
			print("group[%s]: %s" % (i, group))
		print()
	return 0

if __name__ == "__main__":
	sys.exit(main(sys.argv))
